apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-simple-app
  labels:
    name: ahmed-eldaly
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ahmed-eldaly
  template:
    metadata:
      labels:
        name: ahmed-eldaly
    spec:
      containers:
      - name: kubernetes-simple-app
        image: ahmedeldaly097/kubernetes-simple-app:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    name: ahmed-eldaly
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000